const ENCRYPTED_FILE_EXTENSION_ENCRYPTED = 'encrypted';
const ENCRYPTED_FILE_EXTENSION_MDENC = 'mdenc';

export const ENCRYPTED_FILE_EXTENSION_DEFAULT = ENCRYPTED_FILE_EXTENSION_MDENC;


export const ENCRYPTED_FILE_EXTENSIONS = [
	ENCRYPTED_FILE_EXTENSION_MDENC,
	ENCRYPTED_FILE_EXTENSION_ENCRYPTED
];

export const VIEW_TYPE_ENCRYPTED_OUTLINE = 'meld-encrypt-outline';